### PR TITLE
Create requirements.txt

### PR DESCRIPTION
**Pull request by lnick**

### CODE REVIEW

**Comment by rochacbruno** [comment]
The requirementes is within requirements folder

**Comment by rochacbruno** [comment]
https://github.com/quokkaproject/quokka/tree/development/requirements

**Comment by rochacbruno** [comment]
@lnick  why are you including this? is there a specific reason?

**Comment by lnick** [comment]
Hi Bruno.
It's my fault. Sorry for that.
I worked with forked repository and tried to add this file just for 
testing. I clicked "Pull request" by mistake.
Again sorry.

**Pull request closed without merging**
