### PR TITLE
Fix gettext alias in python file.

### PR DESCRIPTION
**Pull request by xiaohanyu**
There're still some work to do for html file.

### CODE REVIEW

**Comment by ellisonleao** [comment]
@xiaohanyu  can you please fix the tests so i can merge? thanks!

**Comment by xiaohanyu** [comment]
Weird, why this will cause import error, not quite understand.

```
======================================================================
ERROR: Failure: ImportError (cannot import name _l)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/virtualenv/python2.7/local/lib/python2.7/site-packages/nose/loader.py", line 413, in loadTestsFromName
    addr.filename, addr.module)
  File "/home/travis/virtualenv/python2.7/local/lib/python2.7/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/home/travis/virtualenv/python2.7/local/lib/python2.7/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/home/travis/build/pythonhub/quokka/quokka/__init__.py", line 15, in <module>
    from .core.admin import create_admin
  File "/home/travis/build/pythonhub/quokka/quokka/core/admin/__init__.py", line 9, in <module>
    from ..models import (Link, Config, SubContentPurpose, ChannelType,
  File "/home/travis/build/pythonhub/quokka/quokka/core/models.py", line 11, in <module>
    from quokka.core.admin import _l
ImportError: cannot import name _l
```

**Comment by xiaohanyu** [comment]
Problem found. Ah, I've made a mistake to do circular import, damn.

**Comment by xiaohanyu** [comment]
Travis didn't start automatically on the amending patch. I don't know why.

**Comment by rochacbruno** [comment]
@xiaohanyu I dont know what to do with this, since travis failed, can you send a new commit on this PR, oe if you say that tested locally and worked well I will merge.

**Comment by xiaohanyu** [comment]
Hi, @rochacbruno 

Never mind. I'm still working to improve babel/i18n to this project. I'm sure this works locally and pass the `make test` in the second commit. The problem of first commit is circular import, which means that you `import A` inside module `A`, and I've changed it to python's relative import, and it works.

**Comment by rochacbruno** [comment]
@xiaohanyu  should I merge this, or wait for other implementations?

**Comment by xiaohanyu** [comment]
Oh, sorry. 

Just merge it, and improvement commit will come on.

**Comment by ellisonleao** [comment]
Merged. The PEP8 error you can fix later (but don't forget, please!). Thanks @xiaohanyu  !

**Pull request merged**
