### PR TITLE
Hide channels behind roles 

### PR DESCRIPTION
**Pull request by hypknowsys**
Hi Bruno,

thanks for your complete code. Yesterday I built it in.

The included code snippets now allow to control every channel with a corresponding role.

Features:
1. In Admin-Mode a channel has now an input field where you can add a role to a channel
2. the role will be saved in Mongo-DB
3. if a channel has no role it will be displayed to everybody
4. if a user has a role which is mentioned in the channel the channel (and content) will be displayed
5. IF NOT: the user will be logout AND redirected to channel redirect_url ("/" by default)

Bruno, if you like the code merge it with the master of your branch.

Greetings from Germany, always nice to work with you,

Henner

### CODE REVIEW

**Comment by rochacbruno** [comment]
:+1: 

As the code did not passed the tests I will review and comment here, since it is passing I will merge for sure!!

**Comment by rochacbruno** [comment]
@hypknowsys the errors are styling errors only, the code is ok.

```
$ pip install -r requirements_test.txt
$ make test
quokka/core/models.py:225:80: E501 line too long (80 > 79 characters)
quokka/core/views.py:59:1: W293 blank line contains whitespace
quokka/core/views.py:60:1: W293 blank line contains whitespace
quokka/core/views.py:61:9: E303 too many blank lines (2)
quokka/core/views.py:70:1: W293 blank line contains whitespace
quokka/core/views.py:71:9: E303 too many blank lines (2)
quokka/core/views.py:72:42: E261 at least two spaces before inline comment
quokka/core/views.py:74:1: W293 blank line contains whitespace
quokka/core/views.py:75:1: W293 blank line contains whitespace
quokka/core/views.py:76:1: W293 blank line contains whitespace
quokka/core/views.py:77:1: W293 blank line contains whitespace
quokka/core/views.py:80:9: E303 too many blank lines (7)
make: *** [pep8] Error 1
```

Can you fix them? then run locally:

```
$ pip install -r requirements_test.txt
$ make test
```

And if returns "OK" commit to be merged!

Thanks;

**Comment by hypknowsys** [comment]
Hi Bruno,
I will fix it: but not today. 

Talk soon,

Henner

**Comment by rochacbruno** [comment]
:+1:

**Comment by hypknowsys** [comment]
Hi Alexandre, thanks for fixing.

**Pull request merged**
