### PR TITLE
Changed the port parameter to int.

### PR DESCRIPTION
**Pull request by Bernardoow**
A type parameter has been added in the port parameter declaration to make explicit that it is integer.

### CODE REVIEW

**Comment by Bernardoow** [comment]
Wait a moment. I checking another thing.

**Comment by Bernardoow** [comment]
Hey @rochacbruno, I found one bug in this implemention. Can do Undo this? =/
The statics file no more is loading. Only at port 5000.

I think when I tested in another ports some cache stay in browser.

**Comment by Bernardoow** [comment]
I found the problem. 
I need update SITEURL to url 127.0.0.1 + port.

**Comment by rochacbruno** [comment]
@Bernardoow So do you think it is better to revert?

**Comment by Bernardoow** [comment]
I will fix that .

I think I need update this thing:
https://github.com/rochacbruno/quokka/blob/568e743d7c64e457202715909879d7bf9842a3a6/quokka/core/flask_dynaconf.py#L61

**Comment by rochacbruno** [comment]
Got it! we need to make that setting dynamic

**Comment by rochacbruno** [comment]
@Bernardoow one workarounf would be in `runserver` command we temper the `app.theme_context['SITEURL']` and all other places it is changed.

**Comment by Bernardoow** [comment]
If you know how change it fast.. 
I will take some time to do it. I am newbiee with this code yet.  =/

**Comment by rochacbruno** [comment]
@Bernardoow done! https://github.com/rochacbruno/quokka/commit/286a17c2fd31249361720eeb8b9a20770e212e44

**Comment by Bernardoow** [comment]
Mee too !! But your impletions is better

**Comment by Bernardoow** [comment]
https://github.com/Bernardoow/quokka/blob/085f930d11fb8da84b23dacf283bcc233ee92b9d/quokka/cli.py#L57

**Comment by rochacbruno** [comment]
nice! I have used the `f""` strings and ommited the `https` using only `//` so it is dynamically loaded by the current used schema.

**Comment by Bernardoow** [comment]
Ah ok !! Thanks !!

**Pull request merged**
